"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.createApp = exports.initMethodAsync = exports.customInjectFn = exports.injectLazy = exports.override = exports.Define = exports.define = exports.injectAliasFactory = exports.lazy = exports.injectAlias = exports.injectArray = exports.injectDictionary = exports.injectObjectProperty = exports.injectValue = exports.aliasFactory = exports.alias = exports.injectFactoryMethod = exports.injectFactory = exports.injectParam = exports.initMethod = exports.inject = exports.factory = exports.singleton = exports.Injector = exports.dynamicFactory = exports.customParam = void 0;
const app_1 = require("./lib/app");
const appolo_inject_1 = require("appolo-inject");
Object.defineProperty(exports, "alias", { enumerable: true, get: function () { return appolo_inject_1.alias; } });
Object.defineProperty(exports, "aliasFactory", { enumerable: true, get: function () { return appolo_inject_1.aliasFactory; } });
Object.defineProperty(exports, "define", { enumerable: true, get: function () { return appolo_inject_1.define; } });
Object.defineProperty(exports, "Define", { enumerable: true, get: function () { return appolo_inject_1.Define; } });
Object.defineProperty(exports, "factory", { enumerable: true, get: function () { return appolo_inject_1.factory; } });
Object.defineProperty(exports, "initMethod", { enumerable: true, get: function () { return appolo_inject_1.initMethod; } });
Object.defineProperty(exports, "inject", { enumerable: true, get: function () { return appolo_inject_1.inject; } });
Object.defineProperty(exports, "injectAlias", { enumerable: true, get: function () { return appolo_inject_1.injectAlias; } });
Object.defineProperty(exports, "injectAliasFactory", { enumerable: true, get: function () { return appolo_inject_1.injectAliasFactory; } });
Object.defineProperty(exports, "injectArray", { enumerable: true, get: function () { return appolo_inject_1.injectArray; } });
Object.defineProperty(exports, "injectDictionary", { enumerable: true, get: function () { return appolo_inject_1.injectDictionary; } });
Object.defineProperty(exports, "injectFactory", { enumerable: true, get: function () { return appolo_inject_1.injectFactory; } });
Object.defineProperty(exports, "injectFactoryMethod", { enumerable: true, get: function () { return appolo_inject_1.injectFactoryMethod; } });
Object.defineProperty(exports, "injectLazy", { enumerable: true, get: function () { return appolo_inject_1.injectLazy; } });
Object.defineProperty(exports, "injectObjectProperty", { enumerable: true, get: function () { return appolo_inject_1.injectObjectProperty; } });
Object.defineProperty(exports, "Injector", { enumerable: true, get: function () { return appolo_inject_1.Injector; } });
Object.defineProperty(exports, "injectParam", { enumerable: true, get: function () { return appolo_inject_1.injectParam; } });
Object.defineProperty(exports, "injectValue", { enumerable: true, get: function () { return appolo_inject_1.injectValue; } });
Object.defineProperty(exports, "lazy", { enumerable: true, get: function () { return appolo_inject_1.lazy; } });
Object.defineProperty(exports, "override", { enumerable: true, get: function () { return appolo_inject_1.override; } });
Object.defineProperty(exports, "singleton", { enumerable: true, get: function () { return appolo_inject_1.singleton; } });
Object.defineProperty(exports, "dynamicFactory", { enumerable: true, get: function () { return appolo_inject_1.dynamicFactory; } });
Object.defineProperty(exports, "customInjectFn", { enumerable: true, get: function () { return appolo_inject_1.customInjectFn; } });
Object.defineProperty(exports, "initMethodAsync", { enumerable: true, get: function () { return appolo_inject_1.initMethodAsync; } });
Object.defineProperty(exports, "customParam", { enumerable: true, get: function () { return appolo_inject_1.customParam; } });
var util_1 = require("./lib/util/util");
Object.defineProperty(exports, "Util", { enumerable: true, get: function () { return util_1.Util; } });
var appolo_event_dispatcher_1 = require("appolo-event-dispatcher");
Object.defineProperty(exports, "EventDispatcher", { enumerable: true, get: function () { return appolo_event_dispatcher_1.EventDispatcher; } });
var launcher_1 = require("./lib/launcher/launcher");
Object.defineProperty(exports, "Launcher", { enumerable: true, get: function () { return launcher_1.Launcher; } });
var filesLoader_1 = require("./lib/loader/filesLoader");
Object.defineProperty(exports, "FilesLoader", { enumerable: true, get: function () { return filesLoader_1.FilesLoader; } });
var app_2 = require("./lib/app");
Object.defineProperty(exports, "App", { enumerable: true, get: function () { return app_2.App; } });
var module_1 = require("./lib/modules/module");
Object.defineProperty(exports, "Module", { enumerable: true, get: function () { return module_1.Module; } });
var events_1 = require("./lib/interfaces/events");
Object.defineProperty(exports, "Events", { enumerable: true, get: function () { return events_1.Events; } });
var pipelineContext_1 = require("./lib/pipelines/pipelineContext");
Object.defineProperty(exports, "PipelineContext", { enumerable: true, get: function () { return pipelineContext_1.PipelineContext; } });
var decorators_1 = require("./lib/decoretors/decorators");
Object.defineProperty(exports, "mixins", { enumerable: true, get: function () { return decorators_1.mixins; } });
Object.defineProperty(exports, "bootstrap", { enumerable: true, get: function () { return decorators_1.bootstrap; } });
Object.defineProperty(exports, "module", { enumerable: true, get: function () { return decorators_1.module; } });
Object.defineProperty(exports, "throttle", { enumerable: true, get: function () { return decorators_1.throttle; } });
Object.defineProperty(exports, "bind", { enumerable: true, get: function () { return decorators_1.bind; } });
Object.defineProperty(exports, "delay", { enumerable: true, get: function () { return decorators_1.delay; } });
Object.defineProperty(exports, "debounce", { enumerable: true, get: function () { return decorators_1.debounce; } });
Object.defineProperty(exports, "cache", { enumerable: true, get: function () { return decorators_1.cache; } });
Object.defineProperty(exports, "once", { enumerable: true, get: function () { return decorators_1.once; } });
Object.defineProperty(exports, "interval", { enumerable: true, get: function () { return decorators_1.interval; } });
Object.defineProperty(exports, "before", { enumerable: true, get: function () { return decorators_1.before; } });
Object.defineProperty(exports, "after", { enumerable: true, get: function () { return decorators_1.after; } });
Object.defineProperty(exports, "pipeline", { enumerable: true, get: function () { return decorators_1.pipeline; } });
Object.defineProperty(exports, "pipelineInstance", { enumerable: true, get: function () { return decorators_1.pipelineInstance; } });
Object.defineProperty(exports, "pipelineType", { enumerable: true, get: function () { return decorators_1.pipelineType; } });
exports.createApp = function (options) {
    return new app_1.App(options);
};
//# sourceMappingURL=index.js.map