"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const app_1 = require("./lib/app");
var util_1 = require("./lib/util/util");
exports.Util = util_1.Util;
var event_dispatcher_1 = require("./lib/events/event-dispatcher");
exports.EventDispatcher = event_dispatcher_1.EventDispatcher;
var launcher_1 = require("./lib/launcher/launcher");
exports.Launcher = launcher_1.Launcher;
var filesLoader_1 = require("./lib/loader/filesLoader");
exports.FilesLoader = filesLoader_1.FilesLoader;
var rocket_inject_1 = require("rocket-inject");
exports.Injector = rocket_inject_1.Injector;
exports.singleton = rocket_inject_1.singleton;
exports.factory = rocket_inject_1.factory;
exports.inject = rocket_inject_1.inject;
exports.initMethod = rocket_inject_1.initMethod;
exports.injectParam = rocket_inject_1.injectParam;
exports.injectFactory = rocket_inject_1.injectFactory;
exports.injectFactoryMethod = rocket_inject_1.injectFactoryMethod;
exports.alias = rocket_inject_1.alias;
exports.aliasFactory = rocket_inject_1.aliasFactory;
exports.injectValue = rocket_inject_1.injectValue;
exports.injectObjectProperty = rocket_inject_1.injectObjectProperty;
exports.injectDictionary = rocket_inject_1.injectDictionary;
exports.injectArray = rocket_inject_1.injectArray;
exports.injectAlias = rocket_inject_1.injectAlias;
exports.injectAliasFactory = rocket_inject_1.injectAliasFactory;
exports.define = rocket_inject_1.define;
var app_2 = require("./lib/app");
exports.App = app_2.App;
var module_1 = require("./lib/modules/module");
exports.Module = module_1.Module;
var decorators_1 = require("./lib/decorators");
exports.mixins = decorators_1.mixins;
exports.bootstrap = decorators_1.bootstrap;
exports.module = decorators_1.module;
exports.create = function (options) {
    return new app_1.App(options);
};
//# sourceMappingURL=index.js.map